# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
---

version: "2"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: jupyter/kernel-gateway-nginx
    ports:
      - "8080:80" # for testing proxied access to the kernel gateway from outside docker
    depends_on:
      - kernel_gateway

  kernel_gateway:
    build:
      context: .
      dockerfile: Dockerfile.kg
    ports:
      - "8888:8888" # for testing direct access to the kernel gateway from outside docker
    image: jupyter/kernel-gateway
    environment:
      KG_ALLOW_ORIGIN: '*'

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      BASE_GATEWAY_HTTP_URL: http://nginx/jupyter/v1/12345678-1234-1234-1234-123456789012
      # see https://github.com/jupyter/jupyter-js-services/issues/158 about username/password here
      BASE_GATEWAY_WS_URL: ws://fakeuser:fakepass@nginx/jupyter/v1/12345678-1234-1234-1234-123456789012
    depends_on:
      - nginx
