version: "2"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: jupyter/kernel-gateway-nginx
    ports:
      - "8080:80"
    depends_on:
      - kernel_gateway
    links:
      - kernel_gateway

  kernel_gateway:
    build:
      context: .
      dockerfile: Dockerfile.kg
    image: jupyter/kernel-gateway
    environment:
      KG_ALLOW_ORIGIN: '*'
