# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

name: got-scotch-api
dependencies:
- notebook=4.2
- pandas=0.17.1
- pip
- pip:
    - git+https://github.com/jupyter/kernel_gateway